apiVersion: v1
kind: Service
metadata:
  name: {{ include "selenoid-kube.fullname" . }}
  labels:
    {{- include "selenoid-kube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: selenoid
      protocol: TCP
      name: selenoid
  selector:
    {{- include "selenoid-kube.selectorLabels" . | nindent 4 }}
