
apiVersion: v1
kind: Service
metadata:
  name: {{ include "selenoid-kube.fullname" . }}-ui
  labels:
    {{- include "selenoidUI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: selenoid-ui
      protocol: TCP
      name: http
  selector:
    {{- include "selenoidUI.selectorLabels" . | nindent 4 }}
